### ISSUE TITLE
Application Hang

### ISSUE THREAD

**Issue by bohbra** [DarkIrata/AmiiboSN-Changer#1]
When I set the amount of duplicates to around 30 or more, the application hangs with no indication that it's working.  No matter how long I let it set there, it's not creating all the duplicates until I force close it using the task manager.

I fixed this myself by doing something like this:

```C#
process.OutputDataReceived += (o, eventArgs) => AppendOutputLine(eventArgs.Data);
process.Start();
process.BeginOutputReadLine();
process.WaitForExit(); 
```

The real time feedback is nice, especially when creating a lot of duplicates.

**Comment by DarkIrata** [comment]
Hi,
i just checked it and i see some other problems with it. 
Trying to fix it asap! :)

**Comment by DarkIrata** [comment]
Should be fixed and run much better with the new release version.
Feel free to reopen if the problem still exists. 
https://github.com/DarkIrata/AmiiboSN-Changer/releases/tag/v1.1.0.0

Thanks for reporting.
