### ISSUE TITLE
File in use error

### ISSUE THREAD

**Issue by bohbra** [DarkIrata/AmiiboSN-Changer#2]
The latest update (1.1.0.0) is great, but I'm getting file in use by another process error for some of the files.  Usually it's around 3 out of a 100 files that get this error.

I'm also seeing a lot of "COM Surrogate" processes, not sure if that is the cause of the issue or not but thought I would let you know.

**Comment by DarkIrata** [comment]
The process should be the instances of the amiitool because its called so fast so often.

Do you get the "used by" from the asnc tool or from copying result files? 
If its in the asnc tool, how many input files do you set?

**Comment by bohbra** [comment]
Did more testing and discovered it was an issue with running asnc from inside a dropbox folder.  I'm assuming dropbox was fighting for files being updated.  It now runs pretty reliably outside of it.  User error, sorry.

**Comment by DarkIrata** [comment]
No problem. Happy to hear that its working fine :)
