### ISSUE TITLE
App Crash when Saving key_retail.bin Path

### ISSUE THREAD

**Issue by Lavince** [DarkIrata/AmiiboSN-Changer#7]
I am having a recurring issue where the app crashes when I attempt to load this file after selecting the path to it. I get the dialogue box to say that it looks valid, and click save, but after a moment of nothing it just closes abruptly.

**Comment by DarkIrata** [comment]
I will look into this today. Can you check the key_retail.bin hash? https://md5file.com/calculator
Should be 160 kbytes
MD5: 45fd53569f5765eef9c337bd5172f937
SHA1: bbdbb49a917d14f7a997d327ba40d40c39e606ce
SHA256: 7f9283654ec1097fbdff31de946651ae60c2854afb544abe8963d389639c710e
SHA512: 5f03ae553fea1bf1ebbbecf7a7006dbaa507e8aa641010297b0c2788b0d73dabb15770253ea08131999aa13a076a1cb86b440f708e8bb671fe3d56fa21f3b048

Just so i can rule out any errors with that when trying to reproduce it.

**Comment by DarkIrata** [comment]
Couldn't reproduce it myself. I added some logging in the new version 
https://github.com/DarkIrata/AmiiboSN-Changer/releases/tag/v3.0.4.1
Please provide the information from the generated Error_----.txt (Found next to the executable file) after getting the error dialog. It should help to fix the issue,

**Comment by Lavince** [comment]
Controlled Folder Access was preventing the program from accessing or editing its own folder. I allowed it now and it seems to proceed after saving without issue.
