### ISSUE TITLE
,,This is Not an amiibo,, fix for FlipperZero 

### ISSUE THREAD

**Issue by Brickleberry19** [DarkIrata/AmiiboSN-Changer#8]
First of all, thank you very much for the program and the time and work that went into it.  

Is it possible to implement this:
https://github.com/turbospok/Flipper-NTAG215-password-converter

**Comment by DarkIrata** [comment]
This should now be fixed in 3.0.5 for the Flipper Zero

**Comment by Brickleberry19** [comment]
Thank you for the fix

**Comment by Brickleberry19** [comment]
Still get the Message ,,this is Not an amiibo,,

**Comment by DarkIrata** [comment]
Do you export them as Flipper .nfc files? Just to make sure, since i dont now if there are already .bin file support.

**Comment by Brickleberry19** [comment]
Yes

**Comment by DarkIrata** [comment]
Mhm. Could you open an exported .nfc and change the last line from
**Page 134: 00 00 00 00**
to
**Page 134: 80 80 00 00**
and check if its working. Any Text Editor is fine.
Was wondering why the py script is doing it, since i couldnt find any information related to it. Maybe the flipper needs the bytes set.

**Comment by Brickleberry19** [comment]
It works now

**Comment by DarkIrata** [comment]
interesting. I will fix it shortly :)

**Comment by Brickleberry19** [comment]
it works now, thank you for integrating it

**Comment by Brickleberry19** [comment]
Hey it me again , I got the Same issue again With the new 4 splatoon amiibo

**Comment by DarkIrata** [comment]
Hmm. Checked the output for the Amiibos. Looks normal to me. Do you get a specific error?

**Comment by Brickleberry19** [comment]
No , only the ,,this is Not an amiibo,, Error on the Switch

**Comment by DarkIrata** [comment]
Checked the dumps from gdrive. It looks like the .bin dumps are not fully functional / are corrupted. Got the same problem with NTAG without even doing anything to them. Try to look for a new dump of them

**Comment by Brickleberry19** [comment]
Which Gdrive?

**Comment by DarkIrata** [comment]
Can't post it. But yeah, looks like either a corrupted version of the amiibo is currently shared or they are not yet supported by the switch (based on what NTAG says to them

**Comment by Brickleberry19** [comment]
If you mean the ones from newamii....they are saved directly from the real amiibo with TagMo. Also, if I convert them with TagMo then they work without any problems

**Comment by DarkIrata** [comment]
Sorry, was late, meant TagMo 😅 and not from newamii, more the gdrive where all files are loosly. But after checking the file hashes, it is the same.
Hmm TagMo shows me for Marina (Side Order) and Pearl (Side Order) that they aren't Switch compatibile

**Comment by Brickleberry19** [comment]
I think this information comes from AmiiboAPI with the game info. Why could it be that the conversion works properly with TagMo but not with your program?

**Comment by DarkIrata** [comment]
hmm wasnt using AmiiboAPI, switched, got the same info. But shouldn't be the problem. 
Do i need something special in TagMo to use the "Save as Flipper" Function? When i press it, nothing happens

**Comment by Brickleberry19** [comment]
There is a TagMo folder on your Phone(in the Download folder) and in that should be a folder named Flipper it should in this folder

**Comment by DarkIrata** [comment]
Ahh okay thanks. 
Can you take a .nfc file from TagMo and one from ASNC and do the following.
Copy from the TagMo file the UID and Page 0 - 4 over to the ASNC and test it. 
If thats not enough, do also Page 133.
Should that still not be enough, Page 5 - 20.

Since i dont have a flipper, i need you to test that for me. Strange thats it only happens with this new amiibos

**Comment by Brickleberry19** [comment]
How do i do that ?

**Comment by DarkIrata** [comment]
You can just open the file with an text editor

**Comment by Brickleberry19** [comment]
Only the UID are different (tested Marina side order)

From TagMo: 04 03 5D D2 2A 68 15
from ASNC : 04 03 5D 2A 68 15 91

**Comment by DarkIrata** [comment]
Based on what i saw, there should be also in Page 0-4 since they are based on the UID. 
Also the other named Pages.
Just replace some parts like noted earlier until it works, so i know which page is incorrect

**Comment by Brickleberry19** [comment]
How i say only the UID are different, Page 0-20 are 1:1 the same 

Edit: Page 133 is also different 
TagMo: 7B 22 10 6A
ASNC : 00 00 00 00

**Comment by Brickleberry19** [comment]
It still says this is Not an amiibo

**Comment by DarkIrata** [comment]
Sorry, was busy.
Can you check again with https://editor.mergely.com/
There should be many more diffenrentials. Since i got way more differentials.
Also, did you  try to add Page 133 to ASNC Output and got still the same error?

**Comment by Brickleberry19** [comment]
Please tell me exactly what I should try, otherwise I feel too stupid for it 😅

**Comment by DarkIrata** [comment]
Hey, sorry busy weeks.
Could you put the content of ASNC's .nfc file in the left Text field and the content of TagMo in the right. It should automaticly hightlight all the differences in the files.
![2024-10-02_08-40-58](https://github.com/user-attachments/assets/9aff2b7e-6ca2-4b24-9761-6728cdad3dee)

And check thats there isnt really many differences.

**Comment by Brickleberry19** [comment]
![image (1).png](https://github.com/user-attachments/assets/28123cce-3277-4087-bc19-eba671a4b555)

![image.png](https://github.com/user-attachments/assets/13c27c53-066e-4695-8e5e-a0a4997f8019)

**Comment by DarkIrata** [comment]
If you copy and overwrite the differences of Page 133 and Page 134 from the right to the left and try it with the flipper, it still doesnt work? 
For me there was way more differences. Also this pages shouldnt effect it. This is really strange

**Comment by Brickleberry19** [comment]
Yes , it doesnt work

**Comment by DarkIrata** [comment]
Looked a little bit more into it. Still cant find the exact reason the Flipper got a problem with the nfc files.
Also, without a Flipper it will be a back and forth with 100 of files to test... If you find which part exactly of the pages needs to be changed, this would be awesome and i can look more into that.

**Comment by Brickleberry19** [comment]
Sorry i never get a Push Message. I Ordered a Flipper and Hope i can Help you more
